name: "Check and test package"

on: [push,pull_request]

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v2.3.1
      - uses: r-lib/actions/setup-pandoc@v2.3.1
      - uses: r-lib/actions/setup-r-dependencies@v2.3.1
        with:
          extra-packages: any::rcmdcheck
          needs: check
      - uses: r-lib/actions/check-r-package@v2.3.1
